module.exports = {
    'likes': '{likes, number} me gusta',
    'logout': 'salir',
    'english': 'Inglés',
    'spanish': 'Español',
    'signup.subheading': 'Regístrate y entérate de las ultimas novedades de nuestra marca y comparte con nosotros la experiencia SF',
    'signup.facebook': 'Iniciar sesión con facebook',
    'signup.text': 'Iniciar sesión',
    'email': 'Correo electrónico',
    'username': 'Nombre de usuario',
    'fullname': 'Nombre completo',
    'password': 'Contraseña',
    'signup.call-to-action':'Regístrate',
    'signup.have-account': '¿Tienes una cuenta?',
    'signin':'Entrar',
    'signin.not-have-account': '¿No tienes una cuenta',
    'language':'Idioma',
    'upload-picture':'Subir foto',
    'upload':'subir'
}